### ISSUE TITLE
CPU and memory limits are too high

### ISSUE THREAD

**Issue by fredychivalan** [prosimcorp/reforma#1]
I am using reform, to patch annotations in Service Account in AWS cloud. But refroma is reserving a lot of CPU resources for me.

It currently has this configuration with two pods within the deployment, for this reason the sum of limits is equal to 1 CPU (1000m). But it really consumes little resource.
```shell
resources:
  limits:
    cpu: 500m
    memory: 128Mi
  requests:
    cpu: 5m
    memory: 64Mi
```
Solution:
After monitoring I propose a solution:

```shell
resources:
  limits:
    cpu: 32m
    memory: 128Mi
  requests:
    cpu: 16m
    memory: 64Mi
```

**Comment by achetronic** [comment]
> I am using reform, to patch annotations in Service Account in AWS cloud. But refroma is reserving a lot of CPU resources for me.
> 
> It currently has this configuration with two pods within the deployment, for this reason the sum of limits is equal to 1 CPU (1000m). But it really consumes little resource.
> ```shell
> resources:
>   limits:
>     cpu: 500m
>     memory: 128Mi
>   requests:
>     cpu: 5m
>     memory: 64Mi
> ```
> Solution:
> After monitoring I propose a solution:
> 
> ```shell
> resources:
>   limits:
>     cpu: 32m
>     memory: 128Mi
>   requests:
>     cpu: 16m
>     memory: 64Mi
> ```

Hello @fredychivalan 

Thank you for reporting the problem.

I agree with you that this operator is requesting a lot of resources. However, the calculation seems to be done a bit randomly, because you are reducing the limits but increasing the requests.

Could you post the output of the following command? this is to know the real resources consumption of the posts

`kubectl top pod <reforma-pod-name>`

After that, I can guide you to promote the changes and bump a new version of the operator

**Comment by fredychivalan** [comment]
Currently I have 3 synchronized resources running, I have done tests with 6 resources which range from 6m to 9m CPU, for this reason I propose an increase in request.

```
NAME                                          CPU(cores)   MEMORY(bytes)   
reforma-controller-manager-78wn                7m          16Mi 
```

**Comment by achetronic** [comment]
> Currently I have 3 synchronized resources running, I have done tests with 6 resources which range from 6m to 9m CPU, for this reason I propose an increase in request.
> 
> ```
> NAME                                          CPU(cores)   MEMORY(bytes)   
> reforma-controller-manager-78wn                7m          16Mi 
> ```

Then, the amount of resources looks good to me. Seem to be reasonable. 

Could you, please, open the PR with the code changes or you need some guidance on that?

**Comment by achetronic** [comment]
> Can you guide me please.

Yes! You have to fork the repository, create a new branch, and change the values [here](https://github.com/prosimcorp/reforma/blob/main/config/manager/manager.yaml#L52-L58), then open a PR with the changes, description and an explanation.

Then we will review if everything is fine and release a new version (we are planning to automate the process in the near future)

**Comment by achetronic** [comment]
Changes merged on [this PR](https://github.com/prosimcorp/reforma/pull/5)
